# Name of the final executable
NAME = fractol

# Compiler and flags
CC = gcc
CFLAGS = -Wall -Wextra -Werror

# Source files
SRCS = fractol_main.c events.c init.c math.c rendering.c handle_strings.c

# Object files (corresponding to the source files)
OBJS = $(SRCS:.c=.o)

# Include and library paths
MINILIBX_PATH = ./minilibx-linux
LIB_FLAGS = -L$(MINILIBX_PATH) -lmlx -lX11 -lXext -lm

# Compilation rules
all: $(NAME)

# Rule for compiling .c files into .o files
%.o: %.c
	$(CC) $(CFLAGS) -I$(MINILIBX_PATH) -c $< -o $@

# Linking object files into the final executable
$(NAME): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) $(LIB_FLAGS) -o $(NAME)

# Clean up object files and other intermediate files
clean:
	rm -f $(OBJS)

# Remove all files generated by the build process
fclean: clean
	rm -f $(NAME)

# Rebuild the project (clean + build)
re: fclean all

.PHONY: all clean fclean re
